CREATE TABLE Blood(
    BloodID INTEGER PRIMARY KEY AUTOINCREMENT, 
    Type CHAR(4) CHECK(Type = 'A' OR Type='A+' OR Type='A-' OR Type='B' OR Type='B+' OR Type='B-' OR Type='O' OR Type='O+' OR  Type='O-' OR Type='AB' OR Type='AB+' OR Type='AB-') UNIQUE NOT NULL
);

CREATE TABLE MaritalStatus(MaritalStatusID INTEGER PRIMARY KEY AUTOINCREMENT, Status VARCHAR(15) NOT NULL);

CREATE TABLE CountryCode(Code SMALLINT PRIMARY KEY, Name NVARCHAR(71) NOT NULL);

CREATE TABLE NumberType(NumberTypeID INTEGER PRIMARY KEY AUTOINCREMENT, Type VARCHAR(10) NOT NULL);

CREATE TABLE Contact
(
	--ContactID INTEGER PRIMARY KEY AUTOINCREMENT,
	ContactNumber INTEGER NOT NULL,
	RefPersonID INTEGER NOT NULL,
	RefNumberTypeID INTEGER NOT NULL,
	RefCountryCode INTEGER NOT NULL,

	PRIMARY KEY(RefPersonID, RefNumberTypeID),
	FOREIGN KEY(RefPersonID) REFERENCES Person(PersonID),
	FOREIGN KEY(RefNumberTypeID) REFERENCES NumberType(NumberTypeID),
	FOREIGN KEY(RefCountryCode) REFERENCES CountryCode(Code)
);

CREATE TABLE Person
(	
	PersonID INTEGER PRIMARY KEY AUTOINCREMENT, 
	Name NVARCHAR(71) NOT NULL, 
	Address NVARCHAR(100) NOT NULL,
	Zip1 INTEGER NOT NULL,
	Zip2 INTEGER NOT NULL,
	Location VARCHAR(51) NOT NULL,
	Sex INT2 NOT NULL,
	Height FLOAT NOT NULL,
	Birthday DATE NOT NULL,
	Birthplace VARCHAR(31) NOT NULL,
	Nationality VARCHAR(31) NOT NULL,
	Profession VARCHAR(31) NOT NULL,
	TaxNumber INT UNIQUE,
	IdentificationCard INT UNIQUE,
	Referer VARCHAR(71),
	Email VARCHAR(256) NOT NULL,
	RefBloodTypeID INTEGER NOT NULL,
	RefMaritalStatusID INTEGER NOT NULL, 
	Active smallint not null default(1),
	
	FOREIGN KEY (RefMaritalStatusID) REFERENCES MaritalStatus(MaritalStatusID),	
	FOREIGN KEY(RefBloodTypeID) REFERENCES Blood(BloodID) 
);

CREATE TABLE Visits
(
	VisitID INTEGER PRIMARY KEY AUTOINCREMENT,
	ParentVisit INTEGER,
	RefPersonID INTEGER NOT NULL,
	
	VisitDate DATE NOT NULL,
	Sleepiness VARCHAR(100) NOT NULL,
	Fatigue VARCHAR(70) NOT NULL,
	Head VARCHAR(70) NOT NULL,
	Tongue VARCHAR(100) NOT NULL,
	Urine VARCHAR(100) NOT NULL,
	Faeces VARCHAR(100) NOT NULL,
	Menstruation VARCHAR(100),
	PulseD VARCHAR(100) NOT NULL,
	PulseE VARCHAR(100) NOT NULL,
	Apal VARCHAR(10) NOT NULL,
	Observations VARCHAR(300),
	Active SMALLINT DEFAULT(1) NOT NULL,

	-- Keys
	FOREIGN KEY(RefPersonID) REFERENCES Person(PersonID),
	FOREIGN KEY(ParentVisit) REFERENCES Visits(VisitID)

);

CREATE TABLE DetailedVisits
(
	DetailedVisitID INTEGER PRIMARY KEY AUTOINCREMENT,
	RefVisitID INTEGER NOT NULL,

	Complaint VARCHAR(100) NOT NULL,
	Anamnesis VARCHAR(300) NOT NULL,
	Weight FLOAT NOT NULL,
	PhysicalAppearance VARCHAR(30) NOT NULL,
	Movement VARCHAR(30) NOT NULL,
	Voice VARCHAR(20) NOT NULL,
	Smell VARCHAR(20) NOT NULL,
	Hypertension SMALLINT NOT NULL,
	Cholesterol SMALLINT NOT NULL,
	Triglyceride SMALLINT NOT NULL,
	Diabetes SMALLINT NOT NULL,
	Transpiration VARCHAR(100) NOT NULL,
	Dehydration VARCHAR(100) NOT NULL,
	Anxiety SMALLINT NOT NULL,
	Irrt SMALLINT NOT NULL,
	Frustration SMALLINT NOT NULL,
	Cry  SMALLINT NOT NULL,
	Verm SMALLINT NOT NULL,
	Ved SMALLINT NOT NULL,
	Brad SMALLINT NOT NULL,
	Prt SMALLINT NOT NULL,
	Aml SMALLINT NOT NULL,
	Alg SMALLINT NOT NULL,
	Irritable SMALLINT NOT NULL,
	Sad SMALLINT NOT NULL,
	Med SMALLINT NOT NULL,
	Melan SMALLINT NOT NULL,
	Hearing VARCHAR(45) NOT NULL,
	Throat VARCHAR(45) NOT NULL,
	Scent VARCHAR(45) NOT NULL,
	Vision VARCHAR(45) NOT NULL,
	SexualActivity VARCHAR(70) NOT NULL,
	Body VARCHAR(70) NOT NULL,
	Abdomen VARCHAR(70) NOT NULL,
	Circulation VARCHAR (70) NOT NULL,
	EatingHabits VARCHAR(300) NOT NULL, 
	
	-- Estrutural Osteopatia
	Prostheses SMALLINT NOT NULL,
	Surgery VARCHAR(100) NOT NULL,
	Weight2 SMALLINT NOT NULL,
	PreviousTreatment VARCHAR(100),
	Pregnancy VARCHAR(100),
	Exams VARCHAR(300) NOT NULL,
	ClinicalAnalysis VARCHAR(200) NOT NULL,
	Medication VARCHAR(300) NOT NULL, 
	Color VARCHAR(40) NOT NULL,
	Escle VARCHAR(60) NOT NULL,
	MedTxt VARCHAR(160) NOT NULL,

	Treatment VARCHAR(300) NOT NULL,

	-- Keys
	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);

CREATE TABLE Pain
(
	PainID INTEGER PRIMARY KEY AUTOINCREMENT,
	RefVisitID INTEGER NOT NULL,
	Type VARCHAR(50) NOT NULL,
	Observation VARCHAR(100) NOT NULL,
	Since VARCHAR(50) NOT NULL,

	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);

CREATE TABLE BloodPressure
(
	RefVisitID INTEGER PRIMARY KEY NOT NULL,
	High SMALLINT NOT NULL,
	Low SMALLINT NOT NULL,
	BPM SMALLINT NOT NULL,

	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);

CREATE TABLE Allergies
(
	AllergyID INTEGER PRIMARY KEY AUTOINCREMENT,
	RefVisitID INTEGER NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Observations VARCHAR(300),
	DeleteDate DATE,

	-- keys
	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);

CREATE TABLE GeneticDisorder
(
	RefVisitID INTEGER NOT NULL,
	GeneticDisorderID INTEGER PRIMARY KEY AUTOINCREMENT,
	Parent VARCHAR(60) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Observations VARCHAR(300),

	-- keys
	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);