CREATE TABLE Visits
(
	VisitID INTEGER PRIMARY KEY AUTOINCREMENT,
	RefPersonID INTEGER NOT NULL,
	Complaint VARCHAR(100) NOT NULL,
	Anamnesis VARCHAR(300) NOT NULL,
	VisitDate DATE NOT NULL,
	Weight FLOAT NOT NULL,
	PhysicalAppearance VARCHAR(30) NOT NULL,
	Movement VARCHAR(30) NOT NULL,
	Voice VARCHAR(30) NOT NULL,
	Smell VARCHAR(30) NOT NULL,
	Hypertension SMALLINT NOT NULL,
	Cholesterol SMALLINT NOT NULL,
	Triglyceride SMALLINT NOT NULL,
	Diabetes SMALLINT NOT NULL,
	Sleepiness VARCHAR(100) NOT NULL,
	Transpiration VARCHAR(100) NOT NULL,
	Dehydration VARCHAR(100) NOT NULL,
	Anxiety SMALLINT NOT NULL,
	Irrt SMALLINT NOT NULL,
	Frustration SMALLINT NOT NULL,
	Cry  SMALLINT NOT NULL,
	Verm SMALLINT NOT NULL,
	Ved SMALLINT NOT NULL,
	Brad SMALLINT NOT NULL,
	Prt SMALLINT NOT NULL,
	Aml SMALLINT NOT NULL,
	Alg SMALLINT NOT NULL,
	Irritable SMALLINT NOT NULL,
	Sad SMALLINT NOT NULL,
	Med SMALLINT NOT NULL,
	Melan SMALLINT NOT NULL,
	Hearing VARCHAR(100) NOT NULL,
	Throat VARCHAR(100) NOT NULL,
	Scent VARCHAR(100) NOT NULL,
	Vision VARCHAR(100) NOT NULL,
	Fatigue VARCHAR(100) NOT NULL,
	SexualActivity VARCHAR(100) NOT NULL,
	Body VARCHAR(100) NOT NULL,
	Abdomen VARCHAR(100) NOT NULL,
	Head VARCHAR(100) NOT NULL,
	Circulation VARCHAR (100) NOT NULL,
	EatingHabits VARCHAR(300) NOT NULL, 
	
	-- Estrutural Osteopatia
	
	-- Keys
	FOREIGN KEY(RefPersonID) REFERENCES Person(PersonID)
);

CREATE TABLE Allergies
(
	AllergyID INTEGER PRIMARY KEY AUTOINCREMENT,
	RefVisitID INTEGER NOT NULL,
	Name VARCHAR(255) NOT NULL,

	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);

CREATE TABLE GeneticDisorder
(
	GeneticDisorderID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE EatingHabits 
(
	Name VARCHAR(100) NOT NULL,
	RefVisitID INTEGER,
	Comment VARCHAR(255),
		
	UNIQUE(Name, RefVisitID),
	FOREIGN KEY(RefVisitID) REFERENCES Visits(VisitID)
);




